CREATE TABLE IF NOT EXISTS public.tb_sensor_evento (
    ID SERIAL PRIMARY KEY,
    ID_DISPOSITIVO TEXT,
    TIMESTAMP_TS TIMESTAMP,
    TEMPERATURA DOUBLE PRECISION,
    HUMIDADE DOUBLE PRECISION,
    LATITUDE DOUBLE PRECISION,
    LONGITUDE DOUBLE PRECISION,
    STATUS TEXT,
    BATERIA DOUBLE PRECISION,
    ALERTA BOOLEAN,
    DT_CARGA TIMESTAMP DEFAULT NOW()
);